swagger: "2.0"
info:
  description: "This is a sample server Petstore server. "
  version: "1.0.0"
  title: "Swagger Petstore"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "petstore.swagger.io"
basePath: "/store"
tags:
- name: "store"
  description: "Access to Petstore orders"
schemes:
- "http"
paths:
  /store/inventory:
    get:
      tags:
      - "store"
      summary: "Returns pet inventories by status"
      description: "Returns a map of status codes to quantities"
      operationId: "getInventory"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: array
            items:
              $ref: '#/definitions/Inventory'
definitions:
  Inventory:
    type: "object"
    properties:
      petId:
        type: "integer"
        format: "int64"
      price:
        type: "number"
        description: "Price to Adopt"
    xml:
      name: "Inventory"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
